# The set of config parameters for the simulation platform.
# See src/types.hpp for detailed definitions.

# We use Manhattan as our case study.
data_file_path:
  vehicle_stations: "/datalog-gitignore/map-data/stations-101.csv"
  network_nodes: "/datalog-gitignore/map-data/nodes.csv"
  shortest_path_table: "/datalog-gitignore/map-data/path-table.csv"
  mean_travel_time_table: "/datalog-gitignore/map-data/mean-table.csv"
  travel_distance_table: "/datalog-gitignore/map-data/dist-table.csv"
  taxi_data: "/datalog-gitignore/taxi-data/manhattan-taxi-20160525.csv"
area_config: 
  lon_min: -74.0300
  lon_max: -73.9030
  lat_min: 40.6950
  lat_max: 40.8825
mod_system_config:
  fleet_config:
    fleet_size: 3000
    veh_capacity: 4
  request_config:
    request_density: 0.2
    max_pickup_wait_time_s: 600
simulation_config:
  simulation_start_time: "2016-05-25 00:00:00"
  cycle_s: 30
  warmup_duration_s: 1800
  simulation_duration_s: 3600
  winddown_duration_s: 3000
output_config:
  datalog_config:
    output_datalog: false
    path_to_output_datalog: "/datalog-gitignore/demo.yml"
  video_config:
    render_video: false
    path_to_output_video: "/media-gitignore/demo.mp4"
    frames_per_cycle: 1  # total frames = simulation_duration_s / (cycle_s / frames_per_cycle)
    replay_speed: 600  # fps = replay_speed / (cycle_s / frames_per_cycle)
