# The set of config parameters for the simulation platform.
# See src/types.hpp for detailed definitions.

# We use Manhattan as our case study.
data_file_path:
  vehicle_stations: "/datalog-gitignore/map-data/stations-101.csv"
  network_nodes: "/datalog-gitignore/map-data/nodes.csv"
  shortest_path_table: "/datalog-gitignore/map-data/path-table.csv"
  mean_travel_time_table: "/datalog-gitignore/map-data/mean-table.csv"
  travel_distance_table: "/datalog-gitignore/map-data/dist-table.csv"
  taxi_data: "/datalog-gitignore/taxi-data/manhattan-taxi-20160525-400k.csv"
  background_map_image: "/media-gitignore/manhattan.jpg"
area_config: 
  lon_min: -74.0300
  lon_max: -73.9030
  lat_min: 40.6950
  lat_max: 40.8825
mod_system_config:
  dispatch_config:
    dispatcher: "SBA"   # 3 options: GI, SBA, OSP
    rebalancer: "NR"   # 2 options: NR (naive rebalancer), NONE
  fleet_config:
    fleet_size: 2000
    veh_capacity: 6
  request_config:
    request_density: 1    # <= 1
    max_pickup_wait_time_min: 5
    max_onboard_detour: 1.3
simulation_config:
  simulation_start_time: "2016-05-25 00:00:00"  # peak hour: 18:00:00 - 20:00:00
  cycle_s: 30
  warmup_duration_min: 30        # 30 min
  simulation_duration_min: 1370   # < 1371 min
  winddown_duration_min: 39      # 39 min
  debug_print: false
output_config:
  datalog_config:
    output_datalog: false
    path_to_output_datalog: "/datalog-gitignore/demo.yml"
  video_config:
    render_video: false   # this requires output_datalog = true
    path_to_output_video: "/media-gitignore/demo.mp4"
    frames_per_cycle: 3  # frame_length = cycle_s / frames_per_cycle (higher frames yields slower speed and longer video)
                         # total frames = simulation_duration_min * 60 / frame_length
    replay_speed: 200    # fps = replay_speed / frame_length (higher speed yields faster speed and shorter video)
